[[pages]]
path = "Pages_CHAT1.py"
name = "GT&C í•™ìŠµë´‡"
icon = "ğŸ¤–"

[[pages]]
path = "Pages_CHAT2.py"
name = "GT&C Q&Aë´‡"
icon = "ğŸ¤–"

[[pages]]
path = "Pages_CHAT3.py"
name = "ê³„ì•½ ë¬¸êµ¬ ì‘ì„±ë´‡"
icon = "ğŸ¤–"

[[pages]]
path = "Pages_CHAT3_2.py"
name = "ê³„ì•½ ë¬¸êµ¬ ë¶„ì„ë´‡"
icon = "ğŸ¤–"


[[pages]]
path = "Pages_CHAT4.py"
name = "Letter ì‘ì„±ë´‡"
icon = "ğŸ¤–"

[[pages]]
path = "Pages_Compare.py"
name = "GT&C íšŒì‚¬ ë³„ ë¹„êµ"
icon = "ğŸ“"

[[pages]]
path = "Pages_Curriculum.py"
name = "GT&C ì»¤ë¦¬í˜ëŸ¼"
icon = "ğŸ“"

[[pages]]
path = "Pages_FAQ.py"
name = "FAQ"
icon = "â“"

[[pages]]
path = "Pages_FAQ2.py"
name = "Advanced FAQ"
icon = "ğŸ§ "

[[pages]]
path = "Pages_Study.py"
name = "Case Study"
icon = "ğŸ’¡"

[[pages]]
path = "Pages_Viewer.py"
name = "GT&C PDFë³´ê¸°"
icon = "ğŸ“‘"
